bind_addr=":8081"
log_level="debug"

database_url="user=postgres password=p02tgre2 dbname=restapi sslmode=disable"

email_sender="email"
smtp_email="smtp.yandex.ru"
password_sender="password"
smtp_port=456



