basePath: /
definitions:
  requests.ParserLogin:
    properties:
      file_name:
        type: string
      login:
        type: string
      monthly:
        type: boolean
      password:
        type: string
      path:
        type: string
    type: object
  responses.Error:
    properties:
      message:
        type: string
    type: object
  responses.ParserResult:
    properties:
      result:
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  description: Swag documentaion for PVSystem24 API
  title: PVSystem24 API
  version: 1.12.0
paths:
  /parser/parse:
    post:
      consumes:
      - application/json
      description: pars site to get informaion about nr
      parameters:
      - description: create new user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.ParserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.ParserResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Parser
      tags:
      - Parser
swagger: "2.0"
